# Generated by Django 5.0.6 on 2024-06-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField()),
                ('credits', models.PositiveIntegerField()),
                ('department', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=100)),
                ('is_elective', models.BooleanField(default=False)),
                ('prerequisites', models.TextField()),
                ('max_capacity', models.PositiveIntegerField()),
                ('duration_weeks', models.PositiveIntegerField()),
            ],
        ),
    ]
